[book]
title = "The Fram Language"
description = "The documentation for the Fram programming language."
language = "en"

[preprocessor.katex]
after = ["links"]

[output.html]
additional-js = ["js/highlight-fram.js"]
